"""organizando pastas de schemas

Revision ID: 5c52a0f1f9ef
Revises: 50f1c6a91ab8
Create Date: 2026-06-10 15:18:21.412554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c52a0f1f9ef'
down_revision: Union[str, Sequence[str], None] = '50f1c6a91ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
